### ISSUE TITLE
update to fastify 4

### ISSUE THREAD

**Issue by franher** [axa-group/bauta.js#17]
Fastify 4 [has been released](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e); therefore, we must upgrade our fastify dependencies to the latest version (fastify, fastify plugins). It's a breaking change.

~~Additionally, we will use the latest version of pino because fastify 4 uses it.~~ It will be done in a separate issue: see #32 

- [x] Bump Fastify 4.x and related fastify/* dependencies to work with Fastify 4.x.
- [x] Update any documentation required to cover the new Fastify 4.x use cases if applicable.

**Comment by javi11** [comment]
Hi @franher I will like to take this one I can open a pr for it :)

**Comment by franher** [comment]
Great, @javi11! I assign the issue to you. Thank you.

**Comment by franher** [comment]
Closed by #31
