### ISSUE TITLE
update eslint rule to avoid unnecessary warning

### ISSUE THREAD

**Issue by Xavier-Redondo** [axa-group/bauta.js#46]
Current rule in .eslintrc

``` "class-methods-use-this": "warn"```

should be changed to:

```"class-methods-use-this": ["error", { "enforceForClassFields": false }]```

This way we remove a warning and we ensure that no class methods use this incorrectly. Further details [here](https://eslint.org/docs/latest/rules/class-methods-use-this).

**Comment by Keith-Web3** [comment]
Hey @Xavier-Redondo, can I work on this or has it been resolved?

**Comment by franher** [comment]
@Keith-Web3 go ahead! PR are welcome! Thank you
